set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V2 [get_ports {switch[0]}]

# 时钟约束设置
create_clock -period 10.000 -name clk [get_ports clk]
create_clock -period 250.000 -name cpu_clk -waveform {0.000 125.000} [get_nets cpu_clk]
create_clock -period 500.000 -name upg_clk -waveform {0.000 250.000} [get_nets upg_clk]

# 声明时钟域间是异步的
set_clock_groups -asynchronous -group [get_clocks cpu_clk] -group [get_clocks upg_clk]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports led_en_button]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property PACKAGE_PIN G3 [get_ports {led[5]}]
set_property PACKAGE_PIN G4 [get_ports {led[6]}]
set_property PACKAGE_PIN F6 [get_ports {led[7]}]
set_property PACKAGE_PIN R15 [get_ports led_en_button]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN B4 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN U2 [get_ports {switch[1]}]
set_property PACKAGE_PIN U3 [get_ports {switch[2]}]
set_property PACKAGE_PIN R1 [get_ports {switch[3]}]
set_property PACKAGE_PIN N4 [get_ports {switch[4]}]
set_property PACKAGE_PIN M4 [get_ports {switch[5]}]
set_property PACKAGE_PIN R2 [get_ports {switch[6]}]
set_property PACKAGE_PIN P2 [get_ports {switch[7]}]
set_property PACKAGE_PIN P3 [get_ports {switch[8]}]
set_property PACKAGE_PIN P4 [get_ports {switch[9]}]
set_property PACKAGE_PIN P5 [get_ports {switch[10]}]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T4} [get_ports tx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports rx]

set_property PACKAGE_PIN T5 [get_ports start_pg]
